const Intensive_lifestyle_therapy = {
    "data": [
        {
            "Name": "Weight_Watchers_1",
            "Source": "Heskha et al. (2003)",
            "ILT_component": "Weight Watchers",
            "Population": "People with Obesity",
            "Start_BMI_ITT": "33.8",
            "Start_BMI_PP": "33.8",
            "Study_year": "1",
        },
        {
            "Name": "Weight_Watchers_2",
            "Source": "Heskha et al. (2003)",
            "ILT_component": "Weight Watchers",
            "Population": "People with Obesity",
            "Study_year": "2",
        },
        {
            "Name": "Intensive_diet_exercise_IDE_1",
            "Source": "STEP 1 or STEP 3",
            "ILT_component": "Intensive diet & exercise (IDE)",
            "Study_year": "1",
            "Percentage_Change_in_BMI_ITT": "-0.0241",
        },
        {
            "Name": "Intensive_diet_exercise_IDE_2",
            "Source": "STEP 1 or STEP 3",
            "ILT_component": "Intensive diet & exercise (IDE)",
            "Study_year": "2",
        },
        {
            "Name": "Intensive_diet_exercise_IDE_3",
            "Source": "STEP 1 or STEP 3",
            "ILT_component": "Intensive diet & exercise (IDE)",
            "Study_year": "3",
            "Percentage_Discontinuing": "0.011580000000000",
        },
        {
            "Name": "Jenny_Craig_center_based_intervention_1",
            "Source": "Rock et al. (2010)",
            "ILT_component": "Jenny Craig - center-based intervention",
            "Population": "Obese and overweight women",
            "Start_BMI_ITT": "33.8",
            "Start_BMI_PP": "33.8",
            "End_BMI_ITT": "30.2",
            "End_BMI_PP": "30",
            "Study_year": "1",
        },
        {
            "Name": "Jenny_Craig_center_based_intervention_2",
            "Source": "Rock et al. (2010)",
            "ILT_component": "Jenny Craig - center-based intervention",
            "Population": "Obese and overweight women",
            "Start_BMI_PP": "30",
            "End_BMI_PP": "30.8",
            "Study_year": "2",
        },
        {
            "Name": "Jenny_Craig_telephone_based_intervention_1",
            "Source": "Rock et al. (2010)",
            "ILT_component": "Jenny Craig - telephone-based intervention",
            "Population": "Obese and overweight women",
            "Start_BMI_ITT": "33.8",
            "Start_BMI_PP": "33.8",
            "End_BMI_ITT": "30.7",
            "End_BMI_PP": "30.5",
            "Study_year": "1",
        },
        {
            "Name": "Jenny_Craig_telephone_based_intervention_2",
            "Source": "Rock et al. (2010)",
            "ILT_component": "Jenny Craig - telephone-based intervention",
            "Population": "Obese and overweight women",
            "Start_BMI_PP": "30.5",
            "End_BMI_PP": "31.3",
            "Study_year": "2",
        },
        {
            "Name": "NutriSystem_1",
            "Source": "Foster (2013)",
            "ILT_component": "NutriSystem",
            "Population": "Patients with type 2 diabetes",
            "Start_BMI_ITT": "35.3",
            "End_BMI_ITT": "32.6",
            "Study_year": "1 (trial length is 6 months, assumes no additional BMI change)",
            "NI_efficacy": "0.004310000000000",
        },
        {
            "Name": "Medifast_1",
            "Source": "Shikany (2013)",
            "ILT_component": "Medifast",
            "Start_BMI_ITT": "40.4",
            "Start_BMI_PP": "40.4",
            "End_BMI_ITT": "38.8",
            "End_BMI_PP": "38.6",
            "Study_year": "1",
        }
    ]
}