central_data_control = {
    "data": [
        {
            "AOM_rebate": "0.30",
            "Contrave_Market_share_original_AOMs": "0",
            "Qsymia_Market_share_original_AOMs": "0",
            "Saxenda_Market_share_original_AOMs": "0",
            "Xenical_Market_share_original_AOMs": "0",
            "Modifiable_AOM_WAC": "100",
            "Include_select_bmi0": true,
            "Include_select_bmi1": true,
            "Include_select_bmi2": true,
            "Include_select_bmi3": true,
            "Percentage_overweight_group_one_comorbidity": "0.771",
            "usermod_effic_inputs_select": "2",
            "usermod_equal_discont_select": "2",
            "discount_rate": "0.03",
            "Do_not_include_semaglutide": false,
            "Include_in_AOM_class": true,
            "Use_Sema_as_only_AOM": false,
            "Applied_half_cycle_correction": "no",
            "Usermod_efficacy_inputs": "no",
            "Inflation_factor": "1.05175120657847",
            "Include_medcosts": true,
            "Include_pharmcosts": true,
            "Include_absenteeism": true,
            "Include_presenteeism": true,
            "Include_disability": true,
            "Include_workerscomp": true,
            "BMI_cap": "60",
            "FullInputs_AOMEff_reduction": "0.0695586367775196",
            "FullInputs_ILTEff_reduction": "0.0298624674556213",
            "Longterm_annual_discontinuation_rate_year_2_onwards": "0.0164",
            "Ratio_of_absenteeism_days_to_presenteeism_days": "3.94",
            "Productivity_decline_on_presenteeism_days": "0.5",
            "DefaultHourlyCompensation": "38.6",
            "DefaultWorkingHoursInADay": "8",
            "OptionalAOMY1EfficacyAssumption": "1",
            "OptionalLifestyle": "1",
            "DefaultWeightWatchers": "0.135",
            "DefaultIDE": "0.83",
            "DefaultJennyCraig": "0.035",
            "DefaultNutriSystem": "0",
            "DefaultMedifast": "0",
            "default_LI_copay": "0",
            "default_dietician_visits": "13",
            "DefaultIDEMembership": "1",
            "AOM_efficacy_calculations_contrve": "2.08333333333333",
            "AOM_efficacy_calculations_qsymia": "1.5625"
        }
    ]
}